version: "3.7"
services:
  appserver:
    image: plot:3.8
    ports:
      - "8000:8000"
      - "9001:9001"
    environment:
      redis_host: 192.168.12.9
      redis_port: 26379
      mysql_host: 192.168.12.9
      mysql_port: 4002
      mysql_name: test
      mysql_password: eHw@dF2%
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/plot-master:/var/www
      - /mnt/FileServer:/var/www/media
      # - /opt/media:/var/www/media
      - ./conf/supervisord-slave.conf:/var/www/supervisord-slave.conf
    command: "supervisord -c /var/www/supervisord-slave.conf"
    networks:
      tier:
        # ipv4_address: 172.19.0.3
networks:
  tier:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
