version: "3.7"
services:
  appserver:
    image: register:3.8
    ports:
      - "8080:8000"
      - "9001:9001"
    environment:
      mysql_host: 192.168.12.10
      mysql_port: 4002
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/leilei/competition:/var/www
      - /root/leilei/FileServer:/var/www/media
      - ./conf/supervisord.conf:/var/www/supervisord.conf
    command: "supervisord -c /var/www/supervisord.conf"
    networks:
      tier:
networks:
  tier:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
