version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /root/media/plot/static:/var/www/static
      - /root/media/FileServer:/var/www/media
    restart: always
    networks:
      tier:
        # ipv4_address: 172.21.0.2
networks:
  tier:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
