version: "3.7"
services:
  app:
    image: plot:3.8
    ports:
      # - "8000"
      - "${SUPERVISOR_PORT}:9001"
    environment:
      - redis_host:${REDIS_HOST}
      - redis_port:${REDIS_PORT}
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CODES_DIR}:/var/www
      - ./config/supervisor:/var/www/config/supervisor
      - ${NFS_DIR}:/var/www/media
    command: "supervisord -c /var/www/config/supervisor/supervisord.conf"
    networks:
      front_tier:
        ipv4_address: ${APP_FRONT_IPV4}
      back_tier:
        ipv4_address: ${APP_BACK_IPV4}
networks:
  back_tier:
    external: true
  front_tier:
    external: true
