version: '3'
services:
  zabbix-mysql:
    image: mariadb:latest
    ports:
        - "3306:3306"
    volumes:
        - ./zabbix/data/mysqllib:/var/lib/mysql
    environment:
        - MYSQL_USER=zabbix
        - MYSQL_DATABASE=zabbix
        - MYSQL_PASSWORD=zabbix
        - MYSQL_ROOT_PASSWORD=iiecas
    restart: always
    networks:
      net:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:centos-latest
    restart: always
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=zabbix
      - DB_SERVER_ROOT_USER=root
      - DB_SERVER_ROOT_PASS=iiecas
      - TZ＝'Asia/Shanghai'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix/zabbixconfig/:/etc/zabbix/
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix/modules:/var/lib/zabbix/modules
      - ./zabbix/enc:/var/lib/zabbix/enc
      - ./zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./zabbix/ssl/certs:/var/lib/zabbix/ssl/certs
      - ./zabbix/ssl/keys:/var/lib/zabbix/ssl/keys
      - ./zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - ./zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - ./zabbix/mibs:/var/lib/zabbix/mibs
    depends_on:
      - zabbix-mysql
    networks:
      net:
  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=iiecas
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ="Asia/Shanghai"
      - TZ＝'Asia/Shanghai'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    links: 
      - zabbix-mysql
      - zabbix-server
    networks:
      net:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.25.0/24