version: '3.7'
services:
  node1:
    image: pxc:latest
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - XTRABACKUP_PASSWORD=${XTRABACKUP_PASSWORD}
      - CLUSTER_NAME=${CLUSTER_NAME}
    volumes:
      - /etc/localtime:/etc/localtime
      - backup:/data
      - ./config/mysql/conf:/etc/mysql/conf.d
      - ./config/mysql/initialdb:/docker-entrypoint-initdb.d
    restart: always
    networks:
      net:
  node2:
    image: pxc:latest
    ports:
      - "23307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - XTRABACKUP_PASSWORD=${XTRABACKUP_PASSWORD}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_JOIN=${CLUSTER_NAME}
    volumes:
      - /etc/localtime:/etc/localtime
      - backup:/data
      # - ./config/mysql/conf:/etc/mysql/conf.d
      # - ./config/mysql/initialdb:/docker-entrypoint-initdb.d
    restart: always
    depends_on: 
      - node1
    networks:
      net:
  lb:
    image: haproxy:cloud
    depends_on: 
      - node1
      - node2
    environment: 
      - ADDITIONAL_SERVICES=pxc:node1,pxc:node2
      - MODE=tcp
      - TCP_PORTS=3306
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "1936:1936"
      # - "80"
    networks:
      net:
volumes:
  backup:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}