version: '3'
services:
  web:
    image: dockercloud/hello-world
  lb:
    image: dockercloud/haproxy
    depends_on:
      - web
    links:
      - web
    environment:
      - ADDITIONAL_SERVICES=project_dir:web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
      - 8888:1936