version: "3.7"
services:
  master:
    image: pxc:latest
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eHw@dF2%
      XTRABACKUP_PASSWORD: eHw@dF2%
      CLUSTER_NAME: pxc-cluster
    volumes:
      - /etc/localtime:/etc/localtime
      - db1:/var/lib/mysql
      - backup:/data
      - ./conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    networks:
      tier:
        ipv4_address: 172.20.0.3
volumes:
  db1:
  backup:
networks:
  tier:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
